workflows:
    learn-workflow:
        name: TodoList Pipeline
        scripts:
          - name: CICD started
            script: echo "Welcome to your CICD setup"
          scripts:
          - name: Build the .app
            script:
                xcodebuild build \
                -workspace "TodoList.xcworkspace" \
                -scheme "TodoList" \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO
        publishing:
          email:
            recipients:
              - ukarora9@gmail.com
