workflows:
    learn-workflow:
        name: TodoList Pipeline
        scripts:
          - name: CICD started
            script: echo "Welcome to your CICD setup"
          - name: Build the .app
            script: xcodebuild build -workspace "TodoList1.xcodeproj" -scheme "TodoList" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        publishing:
          email:
            recipients:
              - ukarora9@gmail.com
